### ISSUE TITLE
phpmoney update require php 8.0

### ISSUE THREAD

**Issue by jirik1h** [AsisTeam/csob-bc#2]
New version 4.0 of phpmoney require php 8.0 which makes this bundle unusable with php 7.x. Would be great to have version, which can run on php 7.x

**Comment by holantomas** [comment]
Thx, for report! I have only one project using this lib on which run on PHP 8. So cannot tests that. Can you try it now please?
https://github.com/AsisTeam/csob-bc/releases/tag/v0.1.0

**Comment by jirik1h** [comment]
Great works fine. Thanks :)
